displayName=Yippee Blue Tears
author=u814me
description=Plays a rewarding sound everytime you get a consecutive blue tear stream on a wall you're already collecting from
tags=tears,guthix,sound,yippee
plugins=com.nickd342.yippeebluetears.YippeeBlueTearsPlugin
build=standard